name: Docker Build & Publish

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Clone My Repository
              uses: actions/checkout@v2

            - name: Login to Docker Hub oooo Cualquier otro Registry
              run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"

            - name: Construir imagen
              run: docker build -t juanfr97/docker-fundamentals:v2 .

            - name: Publicar la imagen
              run: docker push juanfr97/docker-fundamentals:v2